import { type ReactNode } from 'react'
import type { Metadata } from 'next'
import { Providers } from './providers'
import Theme from './theme-provider'
import './globals.css'
import { getDefaultWallets, RainbowKitProvider, } from '@rainbow-me/rainbowkit';
import { Oswald } from 'next/font/google'
import { Poppins } from 'next/font/google'
import { Kumbh_Sans } from 'next/font/google'

const oswald = Oswald({ subsets: ['latin'], weight: ['400', '500', '700'], variable: '--font-oswald' })
const poppins = Poppins({ subsets: ['latin'], weight: ['400', '500', '700'], variable: '--font-poppins' })
const kumbh = Kumbh_Sans({ subsets: ['latin'], weight: ['400', '500', '700'], variable: '--font-kumbh' })

export const metadata: Metadata = {
  title: 'Create Wagmi',
  description: 'Generated by create-wagmi',
}

export default function RootLayout(props: { children: ReactNode }) {
  return (
    <html lang="en" className={`${oswald.variable} ${poppins.variable} ${kumbh.variable}`}>
      <body>
        <main className='mx-auto overflow-hidden'>
          <Providers>
            <RainbowKitProvider >
              <Theme>
                {props.children}
              </Theme>
            </RainbowKitProvider >  
          </Providers>
        </main>
      </body>
    </html>
  )
}
